
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uebqxjjxvfwptwnklwvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVlYnF4amp4dmZ3cHR3bmtsd3Z6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MDI0OTgsImV4cCI6MjA2MDk3ODQ5OH0.VjY9tGZiJ90sGkTNwIyedErpH-BwAZBABNmjru-j9Ec";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
